// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkOSysQKR512vGotQyjfAkhxDPGHx29w',
    appId: '1:1064487535237:web:1a3c09cdd5b170802a9fec',
    messagingSenderId: '1064487535237',
    projectId: 'my-first-regapp',
    authDomain: 'my-first-regapp.firebaseapp.com',
    storageBucket: 'my-first-regapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3vttmVE4EmHRs0GUBvfxeUJR3dYBe4Xg',
    appId: '1:1064487535237:android:5fe805d71299afa42a9fec',
    messagingSenderId: '1064487535237',
    projectId: 'my-first-regapp',
    storageBucket: 'my-first-regapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCShVhHyF3kL3yRIGu9FRcHB_dmAQbIg4c',
    appId: '1:1064487535237:ios:5a6ae27ca688f2422a9fec',
    messagingSenderId: '1064487535237',
    projectId: 'my-first-regapp',
    storageBucket: 'my-first-regapp.appspot.com',
    iosClientId: '1064487535237-d07meaqtgntb9jreuf4kevnt19mb35tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCShVhHyF3kL3yRIGu9FRcHB_dmAQbIg4c',
    appId: '1:1064487535237:ios:5a6ae27ca688f2422a9fec',
    messagingSenderId: '1064487535237',
    projectId: 'my-first-regapp',
    storageBucket: 'my-first-regapp.appspot.com',
    iosClientId: '1064487535237-d07meaqtgntb9jreuf4kevnt19mb35tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.registration',
  );
}
